name: Build Docker Image

on: [ workflow_dispatch ]

jobs:
  build-people:
    runs-on: ubuntu-20.04
    steps:
    - name: Maximize build space
      run:  |
            sudo rm -rf /usr/local/lib/android # will release about 10 GB if you don't need Android
            sudo rm -rf /usr/share/dotnet # will release about 20GB if you don't need .NET
            sudo rm -rf /opt/ghc
            echo "Available storage:"
            df -h

    - uses: actions/checkout@v4

    - uses: docker/setup-qemu-action@v3

    - name: Install vcs
      run: pip3 install vcstool

    - name: Build cabot-people 
      run: | 
        git clone https://github.com/CMU-cabot/cabot-people
        cd ./cabot-people
        ./setup-dependency.sh
        ./build-docker.sh -p -i -w -y -c realsense aarch64
